export const statusCode ={
    'STATUS_CODE_OK': 200,
    'STATUS_CODE_CREATED': 201,
    'STATUS_CODE_NO_FOUND':404,
    'STATUS_CODE_NOT_AUTORIZATION':401,
    'STATUS_CODE_FORM_ERROR':422,
    'STATUS_CODE_400': 400
}